-- Auto-generated by seed-bios-from-cards.mjs
-- 2026-06-26T02:01:47.856Z

UPDATE bni_members SET bio = '方榮久老師
AI 勞動法務顧問｜企業教育講師｜心智圖實戰專家

專注於 AI × 勞動法務 × 心智圖教學，擅長將複雜的勞動法規與企業管理制度，以簡單、視覺化、可落地的方式呈現。長期協助企業降低勞資風險、提升管理效率，', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/fcf8d38e-041f-4509-b428-cbc9246dd39e?ref=bb33eb828306'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '方榮久';
UPDATE bni_members SET bio = '大富燈飾在地經營60年，
專注於住宅與商業空間的燈光規劃與訂製燈具服務。
結合多年經驗與現代照明設計，
從實用機能到空間氛圍，提供最適合的燈光配置建議，
打造舒適、有層次且耐看的空間光環境。', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/936cc968-9557-4f15-abbb-eca2a0f3ebf4?ref=0d31ca51cd8d'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '葉奕廷';
UPDATE bni_members SET bio = '我是系統櫃代表張凱竣

擁有系統櫃工廠和自營系統櫃品牌

提供以下優質服務

1.規劃設計', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/3c9416d0-5ae8-40b1-82e1-f7755285e85b'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '張凱竣';
UPDATE bni_members SET bio = '我是沐微身心靈美學創辦人，專注於頌缽音療，協助企業老闆及員工在生活與工作中找到平衡，我擁有豐富的頌缽資源及身心靈人脈背景，並且結合線下門店及大自然戶外場地，可以帶著大家不僅僅是感受音療，而是真正的放鬆並且看見自己的內在，也帶過不少企業', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/c259da51-7199-4d51-ada7-d3d577366916?ref=6e338ce28269'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '曾筱婷';
UPDATE bni_members SET bio = '代表取締役 | 七海商事　株式会社', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/afb9bfdc-9669-4578-91b8-646fc895467d?ref=57375fa4eec3'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '工藤七海';
UPDATE bni_members SET bio = 'GP石墨烯的誕生，源於對家人健康牽掛的心。感觸於長輩受病痛折磨的辛勞，我們總在想：「如果能提前照顧好身體，是不是就能減少些痛苦？」

這個念頭，成了品牌投入健康領域的初衷。2019年，我', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/1d627510-733c-4d1d-8f49-8efd74b8af6d?ref=f8f062cbe836'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '馮志綱';
UPDATE bni_members SET bio = '負責人 | 吸引力髮型沙龍', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/d1c12877-b247-4636-b88d-c859f5cefb4b?ref=c06acb187f5f'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '呂品蓁';
UPDATE bni_members SET bio = '深耕9年，擅長規劃海外資產配置，傳承，內地金流', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/6180eadc-7cbb-40b7-9c59-afdbbf76b889?ref=f84335d55e72'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '黃湍淳';
UPDATE bni_members SET bio = '享粹咖啡｜把人生的淬鍊，端進每一杯咖啡裡

在新北中和遠東世紀廣場 C 棟，

有一間讓人走進來就能慢下來的咖啡店——

享粹咖啡 PureJoy Cafe。

「享粹」這個名字，來自一份很深的', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/888dc4c5-b0f2-4b90-8cf4-138da949a98b?ref=003bf31171d0'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '呂宜蓁';
UPDATE bni_members SET bio = '▍BNI 資歷
• 母會｜台北市北區／長翔名人堂白金分會
• 長期綠燈會員
• 金質獎章得主
• 新北市西北B區｜金鈺名人堂分會 董事顧問
• 新北市西北', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/11647c30-3ad5-4753-bf4a-35ed4801f9d6?ref=25d4177ff097'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '郭愛珠';
UPDATE bni_members SET bio = '◆全室空間規劃與設計，打造符合個人風格與機能的理想居家。

◆住宅裝修-新成屋、毛胚屋、預售屋客變設計，量身調整格局與風格

◆老屋翻新與中古屋改造-結構評估、動線優化、現代化升級，讓舊宅煥然一新◆小坪數/小宅設計', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/788b2647-dea9-458f-88fe-9e9f7b897352?ref=3e372610a542'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '宋涵識';
UPDATE bni_members SET bio = '您好，我是兆豐證券六罐涼。在銀行端駐點的我

1核心價值不只是提供 style="color: rgb(220, 38,', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/4468cb57-1518-4c0a-9c3c-869709a08008'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '劉冠良';
UPDATE bni_members SET bio = '【公司经营】自主品牌设计和生产服飾/包包/配件品牌，零售/批發市場由百貨公司為主，團體客製化（禮贈品）服務及代工OEM服務

目前百貨專櫃及全省運動用品專賣店都均有販售', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/ben'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '梁虔駖';
UPDATE bni_members SET bio = '總經理 | 喬詩曼國際有限公司', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/1d2382ca-a284-400e-b068-2c9332e1010b?ref=0d4dce68f979'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '黃立喬';
UPDATE bni_members SET bio = '總經理 | 辰翔科技興業有限公司', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/2a7e6ce5-36fd-4a29-a28d-e5275a0922eb?ref=2c89cc8dbae4'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '藍明得';
UPDATE bni_members SET bio = '周玉茹~~美濬華~~

1.OEM 代工 × 各行業禮贈品系統｜創造多元營收', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/ebb5a7f1-b34b-4baf-b722-c82782ee8a84?ref=68f717320a89'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '周玉茹';
UPDATE bni_members SET bio = '我是銀行融資顧問子雯，提供企業與個人銀行貸款媒合服務，包含：青創貸款、企業貸款、房屋貸款及二胎貸款。公司是銀行背景出身，擁有10多間銀行的資源，不用一家家銀行比價而讓您的聯徵多查，收集您的資料前會先簽保密協定及簽定貸款同意書，先與各銀', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/teresa-chen'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '陳子雯';
UPDATE bni_members SET bio = '各位BNI的菁英夥伴們！我是動感國際的負責人——李鴻毅。

很多人一聽到我是「風水命理師」，通常第一反應都是正襟危坐，但我最喜歡的事情其實是「觀察人性」。', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/98a8f050-a8a6-4bb2-88de-d25d052a8288?ref=e7933ce071ac'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '李鴻毅';
UPDATE bni_members SET bio = '方達國際貿易股份有限公司', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/0ac3d82b-9dd4-4092-86e4-b5ceb162e790?ref=1005d51ba6ae'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '李皇家';
UPDATE bni_members SET bio = '和朝創意開發有限公司', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/44bcff67-9de8-417f-8e74-93cff8f1d5f0?ref=3d6f60b70554'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '孫成育';
UPDATE bni_members SET bio = '我是一位當了34年的整形外科醫師 創辦了一個有24年歷史的雅丰醫療事業 提供美容整形手術 / 微整光電治療 / 腸胃健康管理 / 便秘痔瘡 / 靜脈屈張 / 植髮育髮護髮 / 泌尿科 / 減重醫學 / 再生醫學 / 功能醫學 / 中醫', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/9306a603-826e-4adc-ad79-d566ce8983fe?ref=e16441a9ea27'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '張松源';
UPDATE bni_members SET bio = '協理 | 巨將創意廣告股份有限公司', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/06eb2751-e044-4f6a-8fc3-9c7abf3b5b54?ref=5b9f4fca13b4'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '林宗平';
UPDATE bni_members SET bio = '蕭淑蓉 滾滾Rolling

現在也可以叫我蕭美蓉

大寶國際行銷 以統籌大型活動為主，尤其是政府標案與企', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/108500cb-aed0-4023-8c7c-c5e412b5313c?ref=7ba82059d723'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '蕭淑蓉';
UPDATE bni_members SET bio = '串接商品找曉凡，跨境商流超非凡

大家好，我是來自泰國曼谷的楊曉凡 Nick Yan', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/be941196-1533-47e2-98a9-5f1d7bc45eff?ref=570b31be504e'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '楊曉凡';
UPDATE bni_members SET bio = '蔡旻蓉（馨葳）

#新加坡妮芙露股份有限公司 區域總經理

#世界健康養生發展協會 理事長

#AI蓉媽543版主

多年來，我深耕健康保養與大健康服務領域，致力於推廣能自然融入日常的健康保養方', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/91c83633-7d3a-4297-9dea-567f7aa5c0cf'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '蔡馨葳';
UPDATE bni_members SET bio = '呼吸照護：

打呼治療、睡眠檢查

出院準備、呼吸器、氧氣機、攜帶型氧氣機', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/92c7ef8a-c827-4a04-8a24-bf433999a42d'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '游姿菱';
UPDATE bni_members SET bio = '蓋世英雄建築裝修團隊

拆除清運 代表陳姵文

專營室內裝修

保護。拆除。廢棄物清運

合格清運車輛 

愛麗絲不收的垃圾我都收

知名客戶

AT', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/29b1793e-86bc-4230-8f51-a5759baff221?ref=a468113114b6'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '陳姵文';
UPDATE bni_members SET bio = '所長 | 金武吉稅務記帳士事務所', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/4eeb77a1-ea24-46bd-a3b8-e08991d81021?ref=c2572a297bd5'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '劉武嘉';
UPDATE bni_members SET bio = '我是BNI 金虎分會🐯

雲梯搬運車代表 吳侑縉

長期綠燈 會員

曾任🟢秘財🟢品保🟢小組長

公司赫菲斯托斯是韓國DREAM Tns 雲梯搬運設備台灣總代理，

願景是改變', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/536f31a6-299e-4e87-8724-c9ff7cb7460e'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '吳侑縉';
UPDATE bni_members SET bio = '吳庭彰 Wudy

【我是誰？ sty', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/7c320de3-efab-4420-b5dc-5782a89c6e2e?ref=126310da6461'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '吳庭彰';
UPDATE bni_members SET bio = '洪儀君，本身擁有運動傷害防護背景，在指甲保健領域深耕了十幾年，10年前極力推廣運動員的健甲照護，2016年創立了「健甲專家 H.N.P」的品牌，10年後2026年進入事業另一階段，轉型為「足日 zuday」健甲管理中心，不僅是名稱的簡', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/3eb7939c-6cf5-4d60-b401-e1b08a88d82f?ref=e3d5e4aecc89'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '洪儀君';
UPDATE bni_members SET bio = '我是禾雅醫顧的邱耀賢 醫師。

在牙科專業領域中，我不僅專注於美學重建，更深入經營一個特別的服務範疇：睡眠呼吸中止症（OSA）的檢測與精準治療。', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/132086f7-6192-4cc1-b1db-cdbb25a74212?ref=627c65edebed'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '邱耀賢';
UPDATE bni_members SET bio = 'hi 我的商業教育聚焦在新商業思維-互聯網新零售自媒體私域運營商業AI五大戰法,創新盈利八大系統,專門協助台灣中小企業營收增長，並唯一擁有國際頂級資本新加坡軟銀資源協助企業海外IPO', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/a148c1de-859a-4e85-82c2-cf751b3195dc?ref=0d0affce832f'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '詹鴻鵠';
UPDATE bni_members SET bio = '我是一位金融市場深耕10年以上、服務超過 style="color: rgb(220, 38, 3', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/0313cbcb-cead-4949-9012-eb940bf0d459?ref=756f7b21ada1'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '蕭旭庭';
UPDATE bni_members SET bio = '土星垣創意工作室 Saturn Studio

成立於 2016，
專注於親子手作、黏土創作與原創角色設計，
致力打造「不只是上課，而是一起創作回憶」的體驗品牌', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/a7344033-997a-4f97-8344-725b8537c895?ref=da246e847467'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '潘咨吟';
UPDATE bni_members SET bio = '我是微碳石代永續顧問有限公司創辦人，我們專注於陪跑農/企業導入碳管理與ESG策略解方，提供碳盤查、碳足跡、永續白皮書、ESG 發展策略顧問與政府補助資源的服務，陪跑農/企業用永續打造市場競爭力與合作機會。', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/4aeda386-a57c-46ce-8882-4c0b44a5a9dc?ref=b34089dc75b3'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '石珮萱';
UPDATE bni_members SET bio = '很多人都說，認識張婕之後，聊天時都會忍不住看別人的牙齒。

因為一口好牙，不只是健康，更是自信與笑容的關鍵。

我是齒模假牙美學代表張婕。

無論是植牙、牙套、全瓷冠或美白貼片，我都能協助您找到適合的牙醫', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/0a8d993e-8517-4c08-9899-33f7d33cd80f?ref=51f683b77229'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '張婕';
UPDATE bni_members SET bio = '金佑分會產險代表大誠保經經理
我擁有 11 年的銀行金融資歷、5 年的自主創業經驗，以及海內外保險經紀顧問 10 年的專業。因為我自己創過業，我懂當老闆的痛以及經營過程兢兢業業的心情

很多朋友聽到「產險」兩個字，可能', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/82ae8737-ef1d-48fc-9ebe-a46d1a9685bf?ref=ca856b1e9fdb'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '林以晴';
UPDATE bni_members SET bio = '各位BNI的菁英夥伴們！我是動感國際的業務經理——楊妙玲。

我們動', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/24520146-d36f-42bc-9c48-a37c1e806d75?ref=35a1593fa1fe'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '楊妙玲';
UPDATE bni_members SET bio = '醫療財富管理與尊嚴長照系統

我們不賣單一保單，而是透過 14年的風控經驗，為中高端客戶與企業主建構 「抗通膨、保資產、留尊嚴」 的系統化防護網：', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/c0d3ce9c-d245-4787-a8f2-7b6a1638d7c0'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '康彥琳';
UPDATE bni_members SET bio = '擁有 10 年深厚的電商平台營運與數位轉型經驗，致力於協助國際品牌無縫接軌台灣市場。具備敏銳的在地趨勢觀察力與高度同理心，擅長透過精準的市場分析與整合規劃，為海外企業量身打造專屬的線上通路代操策略，大幅降低跨國初入台灣的摸索成本與風', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/11d5c9f4-73a6-4af0-850f-988c57e0d446'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '張文婷';
UPDATE bni_members SET bio = '新北市38年珠寶店：

提供珠寶訂製、鑽石婚對戒、

業績獎勵金牌、年資金幣

黃金玫瑰花禮品、新生兒金飾、小金豆、儲蓄金塊', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/6b5c27c8-477a-44a5-9ca5-a44334a3b263?ref=f11cd1929d03'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '蘇泰勝';
UPDATE bni_members SET bio = '16年金融保險實務經驗，專業的CFP國際認證理財規劃顧問

做的不只是保險，而是幫你把人生的錢安排到位。

資產規劃及傳承最重要的是『生前你掌控，死後你安排』

要完成這個核心目標最重要的是', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/5210emma'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '朱苡菱';
UPDATE bni_members SET bio = '我是長輝分會品牌設計代表 Shawn，來自溫體氣流。

我們相信品牌是一個故事，必須被精準定位，才能刻進人心、自然擴散。溫體氣流最擅長的，就是用「直擊靈魂的定位」與「減法設計的美學」，結合「行銷規劃的厚度」', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/f5d30797-0f93-47e4-9768-8585cec9649d?ref=efc02eafc63e'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '江學洋';
UPDATE bni_members SET bio = '鄭涵秦
瑜伽教室負責人｜艾揚格瑜伽教師

我專注於推廣安全且系統化的艾揚格瑜伽教學，現於台北士林區經營瑜伽教室，提供完整的身心健康課程服務。', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/d1f0b911-a74b-4fcc-ad00-312833006d44?ref=2cb094800d8a'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '鄭涵秦';
UPDATE bni_members SET bio = '🌈🌈你想擁有完美曲線嗎❓你想立馬瘦5公斤嗎❓你想在人群中第一眼就看到你嗎❓

➡️➡️找我就對了，我可以讓你一個月脂肪定位、三個月骨架回正➡️小一個尺碼！

🌷我是一個演', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/51359eda-b4f3-4e12-89e3-806c59256f39?ref=539410dd931a'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '陳語珊';
UPDATE bni_members SET bio = '我是 Kenny，專注跨境資產與房貸套利的財務顧問。深耕金融8年，曾在大學時就背負140萬學信貸，因此更懂得幫客戶把死錢變活錢！

-', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/80275829-e312-4be3-850d-b6cd2677e5f3?ref=cfe3d8b7d424'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '林于翔';
UPDATE bni_members SET bio = '我是長城分會保健食品代表 王彥萍Michelle。

我深耕跨國健康事業已有 6 年時間，專注於為高端養生、企業主及高資產客群', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/f8161b4a-7de0-451e-9e61-4e8db623bc7f?ref=9a66399bfcda'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '王彥萍';
UPDATE bni_members SET bio = '覓．境 (Fwonderlands) 是一家專注於高質感戶外活動規劃、企業團隊建立（Team Building）與秘境探索的專業企劃公司。

創辦人葉書婷（Amanda）擁有 25年的護理師資歷，及15年的內科專科護理師資歷', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/ec5f00b1-9166-43b5-803b-a52dfc9c956a?ref=e29d697e2fe7'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '葉書婷';
UPDATE bni_members SET bio = '曾經沒有業務經驗，做業務三年晉升營業處長

榮獲龍巖鑽石會員（全省僅20位）

代表行客戶：金融業、科技業', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/f181f80f-9c8d-4644-a3d1-666b24bd9520?ref=f79a0fd100aa'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '陳麗惠';
UPDATE bni_members SET bio = '第三次水革命--從「喝乾淨的水」進化到「喝真正有益健康的水」

 target="_blank" rel="noopener noreferrer nofollow" href="https://886.news/arc', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/e783dc6f-bc18-402c-b8a0-2d713b77f49e?ref=5598f861e73d'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '陳易白';
UPDATE bni_members SET bio = '安家堅持，防水不能「一桶塗到底」，而應依不同空間與使用需求，量身設計施

工方案。

外牆與屋頂，會依日照與結構調整層次；浴室與陽台，則依潮氣與排水動線選

擇合適材料。

雖然工序較為繁複，但', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/d69437cd-d5fd-415e-9318-1df632992606?ref=e230771ee826'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '林亞叡';
UPDATE bni_members SET bio = '診所的特殊項目是「OSA 睡眠矯正」

診所會把睡眠檢測機器讓你們帶回飯店睡兩天晚上做出報告檢測，我們會用報告精準地統計出你在夜間睡眠的時候血氧多久以及血氧的狀況還有心率的狀況。

我們只需要到診所一', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/af696ba4-41ae-4d3e-8b91-2985d2ebd70d?ref=ea517386086d'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '謝馥安';
UPDATE bni_members SET bio = '律生活法律事務所是擁有20多位夥伴的法律專業團隊，擅長工程、營造、土木等爭議處理，夥伴除了有律師資格，也有土木技師、土木碩士等跨領域能力。

另外，服務數百間企業客戶，包含上市櫃公司、科技公司、醫療產業（醫美診所、牙醫診所、', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/a6beb421-0314-45ce-a9f9-0c7d4d6d582e?ref=56e6f5829675'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '楊哲瑋';
UPDATE bni_members SET bio = '提供塗裝相關(油漆)工程的各式服務，從建築塗料使用前之規劃到施工，完整落實塗裝工程一站式的服務。施工範圍包含了住家、商空、廠辦及大型集合住宅等，小至30坪大至3萬坪，團隊都能您服務。

服務客戶：台灣立邦塗料(授權服務商)、', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/98d0d0c2-59d1-42e3-8378-c62252ff4087?ref=3b8895b9c2ba'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '黃同慶';
UPDATE bni_members SET bio = '機場接送/包車旅遊/商務接送', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/8046349d-320e-4560-8c11-745e920d4d35'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '林家蔚';
UPDATE bni_members SET bio = '負責人 | 豆韻有限公司', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/6538eff4-e509-4bea-98cc-97751c79172a?ref=34f9e7fe688c'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '張淳瑞';
UPDATE bni_members SET bio = '真心呵護的願景：

創造身心障礙者幸福就業', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/a858869c-00f2-4160-9465-1229839bc905?ref=fbe402f68aac'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '曾惠君';
UPDATE bni_members SET bio = '業務經理 Account Manager | 傑卡創意有限公司 (JCA CREATIVE)', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/1e648d7a-97ba-44c3-afc1-0ac5b388e758?ref=40feb8ebd684'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '楊宜靜';
UPDATE bni_members SET bio = '邏輯教育 | 嘉鸋國際文教', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/9e0b5bb9-f95b-4101-a4d1-b87c32f6891a?ref=227ff507e798'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '吳宜靜';
UPDATE bni_members SET bio = '我是 Eddio 曾士豪，LENDLEND 共同創辦人。LENDLEND 是一個整合商家與消費者的租借平台，主打「先租再買、Try Before You Buy」，讓消費者不用押金、不用押證件，也能更安心地租借戶外、攝影、母嬰、家電、', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/49f7531b-6b99-465d-8f0c-5a3d92bb87e1?ref=148c50636a3e'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '曾士豪';
UPDATE bni_members SET bio = '我是金暘分會 營養師', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/933e5f69-9b87-4fc9-b355-3a91e23c6e85?ref=f66865461ded'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '王思穎';
UPDATE bni_members SET bio = '服務項目

住宅、公司、工廠、風水鑑定、堪輿、招財佈局

紫微斗數、命理諮詢、流年諮詢

姓名論斷、小兒取名、公司行號取名

開運印鑑、神位安奉、祖先安奉

神位規劃、塔位墓園規劃、尋', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/2619fdf8-8e72-4cf4-8908-6c1c5f8867d0?ref=f31da9788b57'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '鍾坤宏';
UPDATE bni_members SET bio = '冷氣買賣、裝潢評估、保養清洗、維修服務', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/789c9cb2-0052-4ba5-b25b-0b8b071c650b?ref=d067203fb556'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '廖筱蘭';
UPDATE bni_members SET bio = '總監 | 力新創意有限公司', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/90a8de9d-87c0-4875-91e0-c33da3ee8e6a?ref=d34a3af6da3d'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '張力文';
UPDATE bni_members SET bio = '業務經理 | 三商美邦人壽 Mercuries Life Insurance', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/6b095d74-f86c-4c27-8299-c4794210b3e6?ref=94f65f68e4db'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '陳沛緹';
UPDATE bni_members SET bio = '院長 · 物理治療師 | 森暉物理治療所', card_link = COALESCE(NULLIF(card_link,''), 'https://namegain.introvista.ai/card/ddf6283a-4b05-44b0-8c53-a08bbf4d0e8a?ref=e63e94bcf8a4'), updated_at = now() WHERE active = true AND regexp_replace(name, '[^\u4e00-\u9fff]', '', 'g') = '洪岳裕';
