-- BNI A Team — 新手教學步驟（可由管理員在 DB 更新，前端動態讀取）
INSERT INTO bni_tutorial_steps (step_order, step_key, title_zh, title_en, body_zh, body_en, tip_zh, tip_en) VALUES
(1, 'welcome',
 '歡迎來到年會', 'Welcome',
 '你好，{name}！你已成功綁定 {branch} 身分。這套系統幫你在 800 人現場快速找到對的人。',
 'Hi {name}! You are bound to {branch}. This app helps you connect with the right people at the event.',
 '教學約 1 分鐘，完成後即可自由使用。', 'About 1 minute — then you are free to explore.'),
(2, 'home',
 '① 首頁 · 瀏覽分會', '① Home · Browse Branches',
 '首頁可依「中山區 / 三蘆區」切換，點分會卡片進入該分會會員名單。',
 'On Home, switch Zhongshan / Sanlu regions and tap a branch card to see members.',
 'Contributor 區塊感謝本次技術支援夥伴。', 'See Contributors for event tech partners.'),
(3, 'search',
 '② 搜尋 · 找人脈', '② Search · Find People',
 '「搜尋」分頁可用姓名、分會、產業關鍵字篩選。點卡片可看詳情與 LINE 聯絡方式。',
 'Search tab: filter by name, branch, or profession. Tap a card for details and LINE.',
 '建議大家填寫產業別與引薦對象（好的／理想／夢幻引薦），搜尋會更準。', 'Encourage peers to fill industry and referral fields for better search.'),
(4, 'ai',
 '③ AI · 智慧配對', '③ AI · Smart Match',
 '說出你的需求（例如「想找做室內設計的會員」），AI 會從名單中推薦最合適的人。',
 'Describe your need (e.g. interior design) and AI recommends matches from the roster.',
 '需網路連線；結果仍請自行確認是否合適。', 'Requires network; always verify fit yourself.'),
(5, 'marks',
 '④ 標記 · 鎖定目標', '④ Marks · Save Targets',
 '想約 1-1 或合作的人請「標記」，存在本機。今日目標：至少標記 5 位夥伴。',
 'Mark people for 1-1 or collaboration — saved on your device. Goal: mark at least 5 today.',
 '標記資料在清除瀏覽器快取前會保留。', 'Marks persist until you clear browser data.'),
(6, 'settings',
 '⑤ 設定 · 字體與語言', '⑤ Settings · Font & Language',
 '右上角可切換中文 / English，以及標準、大字、特大字體，適合現場各年齡層。',
 'Top-right: switch Chinese / English and font size (standard, large, extra large).',
 '字體設定會記住，下次開啟仍生效。', 'Font preference is saved for your next visit.'),
(7, 'goal',
 '準備好了！', 'You are ready!',
 '今天目標：標記 5 位以上夥伴、完成至少 2 次 1-1。祝你在 BNI A Team 年會收穫滿滿！',
 'Today: mark 5+ partners and complete at least 2 1-1s. Have a great BNI A Team event!',
 '點下方按鈕開始，教學狀態會寫入資料庫。', 'Tap below to start — completion is saved to the database.')
ON CONFLICT (step_key) DO UPDATE SET
  step_order = EXCLUDED.step_order,
  title_zh = EXCLUDED.title_zh,
  title_en = EXCLUDED.title_en,
  body_zh = EXCLUDED.body_zh,
  body_en = EXCLUDED.body_en,
  tip_zh = EXCLUDED.tip_zh,
  tip_en = EXCLUDED.tip_en,
  active = true;
