-- BNI A Team — 新手教學步驟（可由管理員在 DB 更新，前端動態讀取）
INSERT INTO bni_tutorial_steps (step_order, step_key, title_zh, title_en, body_zh, body_en, tip_zh, tip_en) VALUES
(1, 'welcome',
 '歡迎來到年會', 'Welcome',
 '你好，{name}！你已成功綁定 {branch} 身分。這套系統幫你在 800 人現場快速找到對的人。',
 'Hi {name}! You are bound to {branch}. This app helps you connect with the right people at the event.',
 '接下來約 2 分鐘：先認識功能，再教你填好媒合名片。', 'About 2 minutes — features first, then your profile card.'),
(2, 'home',
 '① 首頁 · 瀏覽分會', '① Home · Browse Chapters',
 '首頁可依「中山區 / 三蘆區」切換，點分會卡片進入該分會會員名單。',
 'On Home, switch Zhongshan / Sanlu regions and tap a branch card to see members.',
 'Contributor 區塊感謝本次技術支援夥伴。', 'See Contributors for event tech partners.'),
(3, 'search',
 '② 搜尋 · 找人脈', '② Search · Find People',
 '「找人脈」分頁可用姓名、分會、產業關鍵字篩選。點卡片可看詳情與 LINE 聯絡方式。',
 'Connect tab: filter by name, chapter, or profession. Tap a card for details and LINE.',
 '資料填愈完整，被搜到的機會愈高。', 'The richer your profile, the easier others find you.'),
(4, 'ai',
 '③ AI · 智慧配對', '③ AI · Smart Match',
 '說出你的需求（例如「想找做室內設計的會員」），AI 會從名單中推薦最合適的人。',
 'Describe your need (e.g. interior design) and AI recommends matches from the roster.',
 '需網路連線；結果仍請自行確認是否合適。', 'Requires network; always verify fit yourself.'),
(5, 'profile',
 '④ 完善 · 你的媒合名片', '④ Profile · Your match card',
 '請填寫產業別、自我介紹、我有的資源、想認識誰、引薦對象（好的／理想／夢幻）。夥伴搜尋與 AI 都靠這些欄位找到你。',
 'Fill industry, bio, what you offer, who you want to meet, and referrals (Good / Ideal / Dream). Search and AI rely on these fields.',
 '不確定怎麼寫？下方有範本可一鍵套用；有電子名片可帶入自我介紹。', 'Use a one-tap template; import bio from your e-card if available.'),
(6, 'marks',
 '⑤ 標記 · 鎖定目標', '⑤ Marks · Save Targets',
 '想約 1-1 或合作的人請「標記」。今日目標：標記 10 位夥伴、其中至少 10 位「想約 1-1」。',
 'Mark people for 1-1 or collaboration. Goal: 10 partners marked, including 10 for 1-1.',
 '當你標記「想約 1-1」，對方登入後也會看到通知：誰想跟你約 1-1！', 'When you mark 1-1, they get a notification when they log in.'),
(7, 'incoming',
 '⑥ 通知 · 有人想約你', '⑥ Alerts · 1-1 requests',
 '若有人標記「想約 1-1」，你的畫面會跳出通知，顯示對方是誰。記得主動打招呼！',
 'If someone marks you for 1-1, you will see who wants to meet when you are online.',
 '這是雙向媒合：你找人，也會被找到。', 'Matching works both ways — you find people, and people find you.'),
(8, 'settings',
 '⑦ 設定 · 字體與語言', '⑦ Settings · Font & Language',
 '右上角可切換中文 / English，以及標準、大字、特大字體，適合現場各年齡層。',
 'Top-right: switch Chinese / English and font size (standard, large, extra large).',
 '字體設定會記住，下次開啟仍生效。', 'Font preference is saved for your next visit.'),
(9, 'goal',
 '準備好了！', 'You are ready!',
 '今天目標：標記 10 位夥伴、至少 10 次「想約 1-1」，並完善自我介紹。祝你在 BNI A Team 年會收穫滿滿！',
 'Today: mark 10 partners, 10 1-1 intents, and complete your bio. Have a great BNI A Team event!',
 '若還沒填資料，首頁會提醒你；有電子名片可一鍵帶入自我介紹。', 'Home reminds you to complete your profile — import bio from your e-card if you have one.')
ON CONFLICT (step_key) DO UPDATE SET
  step_order = EXCLUDED.step_order,
  title_zh = EXCLUDED.title_zh,
  title_en = EXCLUDED.title_en,
  body_zh = EXCLUDED.body_zh,
  body_en = EXCLUDED.body_en,
  tip_zh = EXCLUDED.tip_zh,
  tip_en = EXCLUDED.tip_en,
  active = true;
